import type { DashboardInfo } from '@/services/api/types';

/** Minimal-but-complete dashboard payload for statistics page tests. */
export function createDashboardInfo(overrides: Partial<DashboardInfo> = {}): DashboardInfo {
  return {
    CurRoundNum: 3,
    CurNumBids: 42,
    CurPrizeAmountEth: 1.5,
    PrizeClaimTs: 0,
    TsRoundStart: 1_700_000_000,
    LastBidderAddr: '0x1111111111111111111111111111111111111111',
    GestureCostEth: 0.01,
    StakingAmountEth: 2.5,
    CosmicGameBalanceEth: 36.1595,
    CharityBalanceEth: 0.5,
    NumDonatedNFTs: 4,
    NumRwalkTokensUsed: 2,
    NumVoluntaryDonations: 1,
    SumVoluntaryDonationsEth: 0.25,
    TotalPrizesPaidAmountEth: 9.1377,
    CgPrizeRowCount: 53,
    NumRaffleNFTWinnersBidding: 3,
    NumRaffleNFTWinnersStakingRWalk: 2,
    CurRoundStats: {
      TotalEthInBidsEth: 2.3294,
      TotalCstInBidsEth: 17053.24,
    },
    MainStats: {
      NumCSTokenMints: 24,
      NumBidsCST: 297,
      NumUniqueBidders: 29,
      NumUniqueWinners: 6,
      NumUniqueDonors: 2,
      NumUniqueStakersCST: 7,
      NumUniqueStakersRWalk: 3,
      TotalRaffleEthDeposits: 0.9879,
      TotalRaffleEthWithdrawn: 2.9636,
      TotalCSTConsumedEth: 84576.37,
      TotalMktRewardsEth: 3000,
      NumMktRewards: 12,
      TotalNamedTokens: 5,
      TotalEthDonatedAmountEth: 30,
      NumCosmicGameDonations: 1,
      SumCosmicGameDonationsEth: 1.7288,
      NumWithdrawals: 2,
      SumWithdrawals: 3.5,
      NumWinnersWithPendingRaffleWithdrawal: 0,
      DonatedTokenDistribution: [],
      StakeStatisticsCST: {
        NumActiveStakers: 3,
        NumDeposits: 0,
        TotalRewardEth: 0,
        TotalTokensMinted: 0,
        TotalTokensStaked: 11,
        UnclaimedRewardEth: 0,
      },
      StakeStatisticsRWalk: {
        NumActiveStakers: 7,
        TotalTokensMinted: 20,
        TotalTokensStaked: 26,
      },
    },
    ...overrides,
  } as unknown as DashboardInfo;
}
