'use client';

import dynamic from 'next/dynamic';
import { createTheme } from '@uiw/codemirror-themes';

const CodeMirror = dynamic(() => import('@uiw/react-codemirror'), { ssr: false });

import { CodeWrapper, MainWrapper, StyledLink } from '@/components/styled';

import { COSMIC_SIGNATURE_CODE } from './cosmicSignatureCode';

const myTheme = createTheme({
  theme: 'light',
  settings: {
    background: 'transparent',
    fontFamily: 'monospace',
  },
  styles: [],
});

const CodeViewer = () => (
  <MainWrapper>
    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
      <div>
        <h4 className="text-2xl font-bold text-primary">Generation Code</h4>
        <div className="mt-4">
          <p className="text-base leading-[1.8]">
            The following code converts the seed generated by the smart contract into images. You
            can also find it on IPFS:
          </p>
          <p className="text-base">
            <StyledLink href="https://cloudflare-ipfs.com/ipfs:/QmWEao2HjCvyHJSbYnWLyZj8HfFardxzuNh7AUk1jgyXTm">
              ipfs:/QmWEao2HjCvyHJSbYnWLyZj8HfFardxzuNh7AUk1jgyXTm
            </StyledLink>
          </p>
        </div>
      </div>
      <div>
        <CodeWrapper className="code-wrapper">
          {
            <CodeMirror
              value={COSMIC_SIGNATURE_CODE}
              theme={myTheme}
              editable={false}
              basicSetup={{ lineNumbers: false, foldGutter: false }}
              height="500px"
              style={{ fontSize: '16px' }}
            />
          }
        </CodeWrapper>
      </div>
    </div>
  </MainWrapper>
);

export default CodeViewer;
