/**
 * Local chain lifecycle: generates a wrapper Hardhat config over the contracts
 * repo's own config (to control the in-memory chain's start time and mining
 * cadence) and starts `hardhat node` from that repo.
 */

import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import type { HarnessConfig } from '../config';
import { CHAIN_ID, harnessPaths } from '../config';
import { jsonRpc, waitFor } from '../rpc';
import { logFileFor, spawnSupervised, type ManagedProcess } from '../processes';

/**
 * Environment expected by the contracts repo's hardhat.config.js. Mode 2 is
 * its "hardhat node server" profile (same flags its own runner scripts use);
 * the preprocessor/assert flags must match how artifacts/ were compiled or
 * the deploy step recompiles from scratch.
 */
export const CONTRACTS_REPO_ENV = {
  HARDHAT_MODE_CODE: '2',
  ENABLE_HARDHAT_PREPROCESSOR: 'true',
  ENABLE_ASSERTS: 'true',
  ENABLE_SMTCHECKER: '1',
} as const;

const WRAPPER_CONFIG_TEMPLATE = `'use strict';
// Generated by the frontend harness (scripts/harness). Do not edit.
// Wraps the contracts repo Hardhat config so the harness can control the
// in-memory chain's initial date (backdated history seeding) and mining.
const base = require(%BASE_CONFIG_PATH%);
const config = base && base.default ? base.default : base;
// Hardhat derives the project root from the config file's directory; this
// wrapper lives outside the contracts repo, so pin the root back explicitly.
config.paths = Object.assign({}, config.paths, { root: %CONTRACTS_DIR% });
config.networks = config.networks || {};
const hardhatNetwork = config.networks.hardhat || {};
config.networks.hardhat = hardhatNetwork;
const startIso = process.env.HARNESS_CHAIN_START_ISO;
if (startIso) {
  hardhatNetwork.initialDate = startIso;
}
hardhatNetwork.mining = {
  auto: true,
  interval: Number(process.env.HARNESS_MINING_INTERVAL_MS || 2000),
  mempool: { order: 'fifo' },
};
hardhatNetwork.allowBlocksWithSameTimestamp = true;
module.exports = config;
`;

export function chainRpcUrl(config: HarnessConfig): string {
  return `http://127.0.0.1:${config.chainPort}`;
}

export interface StartChainOptions {
  /** ISO timestamp for the chain's genesis clock (backdated seeding); omit for "now". */
  startIso?: string;
}

/** Start the Hardhat node and wait until it answers with the expected chain id. */
export async function startChainNode(
  config: HarnessConfig,
  options: StartChainOptions = {},
): Promise<ManagedProcess> {
  const paths = harnessPaths(config);
  mkdirSync(dirname(paths.hardhatConfigFile), { recursive: true });
  writeFileSync(
    paths.hardhatConfigFile,
    WRAPPER_CONFIG_TEMPLATE.replace(
      '%BASE_CONFIG_PATH%',
      JSON.stringify(join(config.contractsDir, 'hardhat.config.js')),
    ).replace('%CONTRACTS_DIR%', JSON.stringify(config.contractsDir)),
  );
  rmSync(logFileFor(config, 'chain'), { force: true });

  const managed = spawnSupervised({
    name: 'chain',
    command: 'npx',
    args: [
      'hardhat',
      '--config',
      paths.hardhatConfigFile,
      'node',
      '--port',
      String(config.chainPort),
    ],
    cwd: config.contractsDir,
    env: {
      ...CONTRACTS_REPO_ENV,
      ...(options.startIso ? { HARNESS_CHAIN_START_ISO: options.startIso } : {}),
    },
    logFile: logFileFor(config, 'chain'),
  });

  await waitFor(
    `Hardhat node on :${config.chainPort}`,
    async () => {
      const chainIdHex = await jsonRpc<string>(chainRpcUrl(config), 'eth_chainId');
      if (Number.parseInt(chainIdHex, 16) !== CHAIN_ID) {
        throw new Error(`unexpected chain id ${chainIdHex}`);
      }
      return true;
    },
    { timeoutMs: 90_000 },
  );
  return managed;
}
