/**
 * Postgres lifecycle via the backend repo's Docker Compose file, namespaced
 * under a harness-specific project so it never collides with other local
 * work. Also registers the deployed contract address book in `cg_contracts`,
 * which is how both the indexer and the dashboard API learn the deployment.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

import type { HarnessConfig } from '../config';
import { harnessPaths } from '../config';
import { logFileFor, runBlocking } from '../processes';

import type { DeployedAddresses } from './deploy';

const execFileAsync = promisify(execFile);

/**
 * The compose file interpolates RPC_URL for its (unused here) ETL services;
 * provide a value so every compose invocation parses. Containers we start
 * (db, migrate) don't consume it.
 */
function composeEnv(config: HarnessConfig): Record<string, string> {
  return { RPC_URL: `http://host.docker.internal:${config.chainPort}` };
}

function composeArgs(config: HarnessConfig): string[] {
  const paths = harnessPaths(config);
  return [
    'compose',
    '-p',
    config.composeProject,
    '-f',
    join(config.backendDir, 'compose.yaml'),
    '-f',
    paths.composeOverrideFile,
  ];
}

function writeComposeOverride(config: HarnessConfig): void {
  const paths = harnessPaths(config);
  mkdirSync(dirname(paths.composeOverrideFile), { recursive: true });
  writeFileSync(
    paths.composeOverrideFile,
    [
      '# Generated by the frontend harness (scripts/harness). Do not edit.',
      'services:',
      '  db:',
      '    ports: !override',
      `      - "${config.dbPort}:5432"`,
      '',
    ].join('\n'),
  );
}

/** True when the Docker daemon answers. */
export async function isDockerUp(): Promise<boolean> {
  try {
    await execFileAsync('docker', ['info', '--format', '{{.ServerVersion}}'], { timeout: 10_000 });
    return true;
  } catch {
    return false;
  }
}

/** On macOS, try to launch Docker Desktop and wait for the daemon. */
export async function ensureDockerUp(waitMs = 90_000): Promise<void> {
  if (await isDockerUp()) return;
  if (process.platform === 'darwin') {
    try {
      await execFileAsync('open', ['-a', 'Docker']);
    } catch {
      // Fall through to the timed wait — the daemon may still be starting.
    }
  }
  const deadline = Date.now() + waitMs;
  while (Date.now() < deadline) {
    if (await isDockerUp()) return;
    await new Promise((resolveSleep) => setTimeout(resolveSleep, 2_000));
  }
  throw new Error(
    'Docker daemon is not running. Start Docker Desktop (or your docker daemon) and retry.',
  );
}

/** Start Postgres (waiting for health) and apply the goose migrations. */
export async function startDatabase(config: HarnessConfig): Promise<void> {
  writeComposeOverride(config);
  await runBlocking({
    name: 'db',
    command: 'docker',
    args: [...composeArgs(config), 'up', '-d', '--wait', 'db'],
    cwd: config.backendDir,
    env: composeEnv(config),
    logFile: logFileFor(config, 'db'),
  });
  // Migrations run from the host: the compose `migrate` service's goose image
  // is not reliably pullable, and `go run` pins goose to the backend's go.mod
  // version. Falls back to a PATH-installed goose binary when Go is absent.
  const dbString = `postgres://rwcg:rwcg@localhost:${config.dbPort}/rwcg?sslmode=disable`;
  const goRunGoose = await runBlocking({
    name: 'migrate',
    command: 'go',
    args: [
      'run',
      'github.com/pressly/goose/v3/cmd/goose',
      '-dir',
      'db/migrations',
      'postgres',
      dbString,
      'up',
    ],
    cwd: config.backendDir,
    logFile: logFileFor(config, 'db'),
  }).then(
    () => true,
    () => false,
  );
  if (!goRunGoose) {
    await runBlocking({
      name: 'migrate',
      command: 'goose',
      args: ['-dir', 'db/migrations', 'postgres', dbString, 'up'],
      cwd: config.backendDir,
      logFile: logFileFor(config, 'db'),
    });
  }
}

/** Run a SQL statement inside the harness Postgres container. */
export async function runSql(config: HarnessConfig, sql: string): Promise<string> {
  const { stdout } = await execFileAsync(
    'docker',
    [
      ...composeArgs(config),
      'exec',
      '-T',
      'db',
      'psql',
      '-U',
      'rwcg',
      '-d',
      'rwcg',
      '-v',
      'ON_ERROR_STOP=1',
      '-c',
      sql,
    ],
    { env: { ...process.env, ...composeEnv(config) } },
  );
  return stdout;
}

/**
 * Register the deployed address book. Column order follows the backend's
 * `cg_contracts` schema (db/migrations/00002_cosmicgame_schema.sql).
 */
export async function registerContractAddresses(
  config: HarnessConfig,
  addresses: DeployedAddresses,
): Promise<void> {
  const values = [
    addresses.cosmicGame,
    addresses.cosmicSignature,
    addresses.cosmicToken,
    addresses.cosmicDao,
    addresses.publicGoodsVault,
    addresses.allocationsWallet,
    addresses.randomWalkNft,
    addresses.anchoringCst,
    addresses.anchoringRwlk,
    addresses.outreachReserve,
    addresses.implementation,
  ]
    .map((addr) => `'${addr}'`)
    .join(',');
  await runSql(config, `DELETE FROM cg_contracts; INSERT INTO cg_contracts VALUES(${values});`);
}

/**
 * Prime the indexer's processing watermark to block 1 so it backfills the
 * seeded history. Without this, cg-etl's startup parameter sync anchors the
 * store watermark at the current chain head and everything mined before its
 * first boot would be skipped. Block 1 is safely empty: the deployment task
 * spends several mining intervals compiling before its first transaction.
 */
export async function primeIndexerWatermark(config: HarnessConfig): Promise<void> {
  await runSql(
    config,
    'INSERT INTO cg_proc_status(last_evt_id, last_block_num) SELECT 0, 1 WHERE NOT EXISTS (SELECT 1 FROM cg_proc_status);',
  );
}

/** Stop harness containers; `wipeVolumes` also destroys the database volume. */
export async function stopDatabase(config: HarnessConfig, wipeVolumes: boolean): Promise<void> {
  writeComposeOverride(config);
  const args = [...composeArgs(config), 'down', '--remove-orphans'];
  if (wipeVolumes) args.push('-v');
  try {
    await execFileAsync('docker', args, {
      timeout: 120_000,
      env: { ...process.env, ...composeEnv(config) },
    });
  } catch (err) {
    // Docker not running means nothing to stop; anything else is reported.
    if (await isDockerUp()) throw err;
  }
}
