import { render, screen, checkA11y } from '@/test-utils';

import CodeViewer from '../CodeViewer';

jest.mock('next/dynamic', () => () => {
  const MockCodeMirror = ({ value }: { value: string }) => (
    <pre data-testid="codemirror">{value.slice(0, 50)}</pre>
  );
  MockCodeMirror.displayName = 'MockCodeMirror';
  return MockCodeMirror;
});

jest.mock('@uiw/codemirror-themes', () => ({
  createTheme: jest.fn(() => ({})),
}));

describe('CodeViewer', () => {
  beforeEach(() => jest.clearAllMocks());

  it('renders the heading', () => {
    render(<CodeViewer />);
    expect(screen.getByText('Generation Code')).toBeInTheDocument();
  });

  it('renders the IPFS description text', () => {
    render(<CodeViewer />);
    expect(
      screen.getByText(/The following code converts the seed generated by the smart contract/),
    ).toBeInTheDocument();
  });

  it('renders the IPFS link', () => {
    render(<CodeViewer />);
    expect(
      screen.getByText('ipfs:/QmWEao2HjCvyHJSbYnWLyZj8HfFardxzuNh7AUk1jgyXTm'),
    ).toBeInTheDocument();
  });

  it('renders the CodeMirror component with Rust code', () => {
    render(<CodeViewer />);
    const codeMirror = screen.getByTestId('codemirror');
    expect(codeMirror).toBeInTheDocument();
    expect(codeMirror.textContent).toContain('extern crate nalgebra');
  });

  it('has no accessibility violations', async () => {
    const { container } = render(<CodeViewer />);
    await checkA11y(container);
  });
});
