import type { Metadata, ResolvingMetadata } from 'next';
import { notFound } from 'next/navigation';
import { getTranslations, setRequestLocale } from 'next-intl/server';

import { getLearnArticle, getLearnContent, getLearnSlugs } from '@/content/learn';

import { Link } from '@/i18n/navigation';
import { getLocaleConfig } from '@/i18n/localeConfig';
import { LANDING_ORIGIN, localeHref, localizeCrossHostHref } from '@/lib/hostRouting';
import { JsonLd, breadcrumbJsonLd, jsonLdInLanguage } from '@/utils/jsonLd';
import { createMetadata } from '@/utils/seo';
import { formatIsoDateLabel } from '@/utils/time';

interface PageProps {
  params: Promise<{ locale: string; slug: string }>;
}

function sectionId(articleSlug: string, index: number): string {
  return `${articleSlug}-section-${index + 1}`;
}

export function generateStaticParams() {
  return getLearnSlugs().map((slug) => ({ slug }));
}

export async function generateMetadata(
  { params }: PageProps,
  parent?: ResolvingMetadata,
): Promise<Metadata> {
  const { locale, slug } = await params;
  setRequestLocale(locale);
  const article = getLearnArticle(slug, locale);
  if (!article) return {};
  const t = await getTranslations({ locale, namespace: 'meta' });
  const metaKey = `learnArticles.${article.slug}`;

  const metadata = createMetadata(
    t(`${metaKey}.title`),
    t(`${metaKey}.description`),
    undefined,
    `/learn/${article.slug}`,
    {
      canonicalHost: 'landing',
      locale,
    },
  );
  if (!parent) return metadata;

  // `openGraph` is shallow-merged by Next.js. Preserve the image generated by
  // the parent Learn segment when this article supplies its own OG copy.
  const parentMetadata = await parent;
  return {
    ...metadata,
    openGraph: {
      ...metadata.openGraph,
      images: parentMetadata.openGraph?.images,
    },
    twitter: {
      ...metadata.twitter,
      images: parentMetadata.twitter?.images,
    },
  };
}

export default async function LearnArticlePage({ params }: PageProps) {
  const { locale, slug } = await params;
  setRequestLocale(locale);
  const article = getLearnArticle(slug, locale);
  if (!article) notFound();
  const { articleUi } = getLearnContent(locale);
  const inLanguage = jsonLdInLanguage(locale);

  const url = localeHref(LANDING_ORIGIN, `/learn/${article.slug}`, locale);
  const articleJsonLd = {
    '@context': 'https://schema.org',
    '@type': article.schemaType,
    headline: article.h1,
    description: article.description,
    url,
    inLanguage,
    datePublished: article.updated,
    dateModified: article.updated,
    author: {
      '@type': 'Organization',
      name: 'Cosmic Signature',
      url: localeHref(LANDING_ORIGIN, '/', locale),
    },
    publisher: {
      '@id': `${LANDING_ORIGIN}/#organization`,
    },
    mainEntityOfPage: url,
  };

  return (
    <main id="main" tabIndex={-1} className="relative mx-auto max-w-4xl px-6 py-24 lg:py-32">
      <JsonLd
        data={[
          breadcrumbJsonLd(
            [
              { name: articleUi.breadcrumbs.homeLabel, path: '/' },
              { name: articleUi.breadcrumbs.learnLabel, path: '/learn' },
              { name: article.h1, path: `/learn/${article.slug}` },
            ],
            localeHref(LANDING_ORIGIN, '/', locale),
          ),
          articleJsonLd,
        ]}
      />
      <nav aria-label={articleUi.breadcrumbs.ariaLabel} className="mb-8 text-sm text-white/60">
        <Link href="/" className="hover:text-white">
          {articleUi.breadcrumbs.homeLabel}
        </Link>
        <span className="mx-2">/</span>
        <Link href="/learn" className="hover:text-white">
          {articleUi.breadcrumbs.learnLabel}
        </Link>
      </nav>

      <article>
        <p className="font-mono text-xs uppercase tracking-[0.28em] text-white/50">
          {articleUi.eyebrow}
        </p>
        <h1 className="mt-4 text-balance text-4xl font-semibold tracking-tight text-white sm:text-5xl">
          {article.h1}
        </h1>
        <p className="mt-6 text-lg leading-8 text-white/78">{article.summary}</p>
        <p className="mt-4 text-sm text-white/50">
          {articleUi.lastUpdatedLabel}
          {getLocaleConfig(locale).wordSpacing ? ' ' : null}
          <time dateTime={article.updated}>
            {formatIsoDateLabel(article.updated, locale)}
          </time> · {articleUi.publisherLabel}
        </p>

        <div className="mt-12 space-y-10">
          {article.sections.map((section, sectionIndex) => (
            <section key={section.heading} aria-labelledby={sectionId(article.slug, sectionIndex)}>
              <h2
                id={sectionId(article.slug, sectionIndex)}
                className="text-2xl font-semibold tracking-tight text-white"
              >
                {section.heading}
              </h2>
              <div className="mt-4 space-y-4">
                {section.body.map((paragraph) => (
                  <p key={paragraph} className="text-base leading-7 text-white/72">
                    {paragraph}
                  </p>
                ))}
              </div>
            </section>
          ))}
        </div>
      </article>

      <aside className="mt-14 rounded-2xl border border-white/10 bg-white/[0.03] p-6">
        <h2 className="text-lg font-semibold text-white">{articleUi.relatedResourcesHeading}</h2>
        <ul className="mt-4 space-y-3">
          {article.related.map((link) => (
            <li key={link.href}>
              <a
                href={localizeCrossHostHref(link.href, locale)}
                className="text-primary underline-offset-4 hover:underline"
              >
                {link.label}
              </a>
            </li>
          ))}
        </ul>
      </aside>
    </main>
  );
}
