import { FadeIn } from './FadeIn';

const ART_TILES = [
  {
    icon: '\uD83C\uDF0F',
    title: 'Simulation',
    color: '#FFB800',
    description:
      '100,000 three-body orbits simulated with a 4th-order Yoshida symplectic integrator from astrophysics research',
  },
  {
    icon: '\uD83C\uDFC6',
    title: 'Selection',
    color: '#00E5FF',
    description:
      'Borda rank aggregation selects the most visually interesting orbit via FFT chaos analysis and equilateralness scoring',
  },
  {
    icon: '\uD83C\uDF08',
    title: 'Spectral Light',
    color: '#FF3D8A',
    description:
      '16 wavelength bins (380-700 nm) render the full visible spectrum with anti-aliased trails and velocity-dependent HDR',
  },
  {
    icon: '\uD83C\uDFA5',
    title: 'Cinema-Grade Output',
    color: '#00D68F',
    description:
      'AgX tonemapping, bloom, nebula overlays, cinematic grading. 16-bit PNG + 30s H.265 video at 60 fps',
  },
];

export function ArtShowcase() {
  return (
    <section className="relative z-[1] py-20 md:py-28 px-6">
      <FadeIn>
        <div className="text-center max-w-[600px] mx-auto mb-12">
          <div
            className="text-xs tracking-[3px] uppercase text-[#6C3CE1] mb-4"
            style={{ fontFamily: "'JetBrains Mono', monospace" }}
          >
            Art & Technology
          </div>
          <h2
            className="font-bold mb-4"
            style={{
              fontFamily: "'Space Grotesk', sans-serif",
              fontSize: 'clamp(1.8rem, 4vw, 2.2rem)',
            }}
          >
            Powered by Physics
          </h2>
          <p className="text-[#F0EDFF]/55 text-base">
            Every NFT&apos;s artwork is generated by simulating the Three Body Problem — three
            celestial bodies locked in gravitational orbit. Real physics. Spectral light. No AI.
          </p>
        </div>
      </FadeIn>

      <div className="max-w-[1100px] mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
        {ART_TILES.map((tile, i) => (
          <FadeIn key={tile.title} delay={i * 100}>
            <div className="bg-[#2D1B69]/20 border border-[#6C3CE1]/15 rounded-2xl p-8 text-center h-full">
              <div className="text-3xl mb-3">{tile.icon}</div>
              <h3
                className="font-bold text-base mb-2"
                style={{ fontFamily: "'Space Grotesk', sans-serif", color: tile.color }}
              >
                {tile.title}
              </h3>
              <p className="text-[#F0EDFF]/50 text-sm leading-relaxed">{tile.description}</p>
            </div>
          </FadeIn>
        ))}
      </div>

      <div className="text-center mt-8">
        <p className="text-[#F0EDFF]/40 text-sm">
          Same seed = same art, every time. Deterministic. Reproducible. Open source (CC0).{' '}
          <strong className="text-[#F0EDFF]">No AI.</strong>
        </p>
      </div>
    </section>
  );
}
