'use client';

import { useEffect, useState } from 'react';

import { Button } from '@/components/ui/button';
import { localClockUtcEpochMs } from '@/lib/activationTime';

type Countdown = {
  days: number;
  hours: number;
  minutes: number;
  seconds: number;
  isLaunched: boolean;
};

/** Remaining time until launch (API ms − local clock as UTC epoch ms). */
function getCountdown(launchTimestampMs: number): Countdown {
  const diff = launchTimestampMs - localClockUtcEpochMs();

  if (diff <= 0) {
    return { days: 0, hours: 0, minutes: 0, seconds: 0, isLaunched: true };
  }

  const totalSeconds = Math.floor(diff / 1000);
  const days = Math.floor(totalSeconds / (24 * 60 * 60));
  const hours = Math.floor((totalSeconds % (24 * 60 * 60)) / (60 * 60));
  const minutes = Math.floor((totalSeconds % (60 * 60)) / 60);
  const seconds = totalSeconds % 60;

  return { days, hours, minutes, seconds, isLaunched: false };
}

/** Calendar + clock in the user's local timezone (browser default, e.g. Mexico). */
function formatLaunchDateLocal(launchTimestampMs: number): string {
  return new Intl.DateTimeFormat(undefined, {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
    timeZoneName: 'short',
  }).format(new Date(launchTimestampMs));
}

/** Same instant, shown in UTC (on-chain / API convention). */
function formatLaunchDateUtc(launchTimestampMs: number): string {
  return new Intl.DateTimeFormat('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
    timeZone: 'UTC',
    timeZoneName: 'short',
  }).format(new Date(launchTimestampMs));
}

type RootLandingPageProps = {
  /** Activation instant in ms (Unix seconds from API × 1000). */
  launchTimestampMs: number;
};

export function RootLandingPage({ launchTimestampMs }: RootLandingPageProps) {
  const [countdown, setCountdown] = useState<Countdown>(() => getCountdown(launchTimestampMs));

  useEffect(() => {
    const tick = () => setCountdown(getCountdown(launchTimestampMs));
    const timerId = window.setInterval(tick, 1000);
    void Promise.resolve().then(tick);
    return () => window.clearInterval(timerId);
  }, [launchTimestampMs]);

  const showCountdown = !countdown.isLaunched;
  const launchDateLabelLocal = formatLaunchDateLocal(launchTimestampMs);
  const launchDateLabelUtc = formatLaunchDateUtc(launchTimestampMs);

  return (
    <div className="relative min-h-screen overflow-hidden px-6 py-12 md:px-10 md:py-16">
      <div className="pointer-events-none absolute inset-0 bg-gradient-to-b from-background via-background/95 to-card/80" />
      <div className="pointer-events-none absolute -top-40 left-1/2 h-[34rem] w-[34rem] -translate-x-1/2 rounded-full bg-primary/15 blur-3xl" />

      <main className="relative mx-auto flex min-h-[calc(100vh-6rem)] max-w-4xl flex-col items-center justify-center text-center">
        <p className="mb-5 text-xs font-semibold uppercase tracking-[0.28em] text-muted-foreground">
          Cosmic Signature
        </p>
        <h1 className="font-display mb-6 text-balance text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl">
          Generative Art
          <span className="block bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
            Born from Physics
          </span>
        </h1>
        <p className="mb-10 max-w-2xl text-balance text-sm leading-relaxed text-muted-foreground sm:text-base">
          A limited collection of one-of-a-kind artworks generated by real three-body gravitational
          simulations. No AI. No manual drawing. Pure deterministic chaos transformed into
          collectible digital art.
        </p>

        {showCountdown && (
          <>
            <div className="mb-12 grid w-full grid-cols-2 gap-3 sm:grid-cols-4 sm:gap-4">
              {[
                { label: 'Days', value: countdown.days },
                { label: 'Hours', value: countdown.hours },
                { label: 'Minutes', value: countdown.minutes },
                { label: 'Seconds', value: countdown.seconds },
              ].map((item) => (
                <div
                  key={item.label}
                  className="rounded-xl border border-white/[0.08] bg-card/80 p-4 backdrop-blur-sm sm:p-6"
                >
                  <div className="font-mono text-4xl font-semibold text-primary sm:text-6xl">
                    {String(item.value).padStart(2, '0')}
                  </div>
                  <div className="mt-2 text-[11px] uppercase tracking-[0.22em] text-muted-foreground sm:text-xs">
                    {item.label}
                  </div>
                </div>
              ))}
            </div>
            <div className="mb-8 space-y-1 text-primary/90">
              <div className="text-sm uppercase tracking-[0.2em]">
                Launches on {launchDateLabelLocal}
              </div>
              <div className="text-xs font-normal normal-case tracking-normal text-muted-foreground">
                {launchDateLabelUtc} (UTC)
              </div>
            </div>
          </>
        )}

        <Button
          asChild
          size="lg"
          className="bg-gradient-to-r from-[#15BFFD] to-[#9C37FD] px-10 font-semibold uppercase tracking-[0.12em] text-white hover:opacity-90"
        >
          <a href="https://app.cosmicsignature.com">Open App</a>
        </Button>
      </main>
    </div>
  );
}
